.build:
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - echo "Building image..."
    - docker build -t $PROJ_IMG .
    - echo "Tagging image $PROJ_IMG $ECR_REPOSITORY/$PROJ_IMG:$BUILD_TAG "
    - docker tag $PROJ_IMG $ECR_REPOSITORY/$PROJ_IMG:$BUILD_TAG
  tags:
    - inviertis-backend
  environment: $CI_COMMIT_REF_SLUG
