deploy:
  stage: deploy
  dependencies:
    - build-test
  script:
    - echo "Deploying version $BUILD_TAG"
    - echo $BUILD_TAG
    - echo $ECS_TEMPLATE
    - envsubst < $ECS_TEMPLATE > ecs-container-definitions.json
    - aws ecs register-task-definition --cli-input-json file://ecs-container-definitions.json --region $ECS_REGION
    - aws ecs update-service --cluster $CLUSTER --service $SERVICE --task-definition $TASK --region $ECS_REGION --force-new-deployment
  
